"""add teacher_id to teacher_attendance

Revision ID: 33c952d11084
Revises: 836255160770
Create Date: 2026-07-21 18:55:23.135370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c952d11084'
down_revision: Union[str, Sequence[str], None] = '836255160770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teacher_teacher_id_fkey'), 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'teacher_id')
    op.add_column('teacher_attendance', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_attendance', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_attendance', type_='foreignkey')
    op.drop_column('teacher_attendance', 'teacher_id')
    op.add_column('teacher', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teacher_teacher_id_fkey'), 'teacher', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
