"""link attendance with student and teacher

Revision ID: 836255160770
Revises: ca9ba1c64d61
Create Date: 2026-07-21 18:24:28.201117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836255160770'
down_revision: Union[str, Sequence[str], None] = 'ca9ba1c64d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'teacher_id')
    # ### end Alembic commands ###
