"""add users table and link user

Revision ID: b0f9a3364b2f
Revises: 33c952d11084
Create Date: 2026-08-02 12:21:08.050733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f9a3364b2f'
down_revision: Union[str, Sequence[str], None] = '33c952d11084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('parent', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'parent', 'users', ['user_id'], ['id'])
    op.drop_column('parent', 'phone_number')
    op.drop_column('parent', 'email')
    op.drop_column('parent', 'name')
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student', 'users', ['user_id'], ['id'])
    op.drop_column('student', 'is_active')
    op.drop_column('student', 'email')
    op.drop_column('student', 'name')
    op.add_column('teacher', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teacher', 'users', ['user_id'], ['id'])
    op.drop_column('teacher', 'phone_number')
    op.drop_column('teacher', 'email')
    op.drop_column('teacher', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'user_id')
    op.add_column('student', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'user_id')
    op.add_column('parent', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('parent', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('parent', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parent', type_='foreignkey')
    op.drop_column('parent', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
