"""link parent to users

Revision ID: b18ee8947fe5
Revises: b0f9a3364b2f
Create Date: 2026-08-03 14:30:42.471218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18ee8947fe5'
down_revision: Union[str, Sequence[str], None] = 'b0f9a3364b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parent', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent', type_='unique')
    # ### end Alembic commands ###
