"""add admin table

Revision ID: bcac782b3a11
Revises: a815421de0cd
Create Date: 2026-08-05 12:13:44.754372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcac782b3a11'
down_revision: Union[str, Sequence[str], None] = 'a815421de0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



 # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_attendance', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('admin')
    # ### end Alembic commands ###
