"""add student_id to attendance

Revision ID: ca9ba1c64d61
Revises: 1a00080aaa16
Create Date: 2026-07-21 18:17:51.426739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9ba1c64d61'
down_revision: Union[str, Sequence[str], None] = '1a00080aaa16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_attendance', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_attendance', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_attendance', type_='foreignkey')
    op.drop_column('student_attendance', 'student_id')
    # ### end Alembic commands ###
